// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// FourierBasis
arma::mat FourierBasis(const arma::vec& pts, int K);
RcppExport SEXP _DepthInfer_FourierBasis(SEXP ptsSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type pts(ptsSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(FourierBasis(pts, K));
    return rcpp_result_gen;
END_RCPP
}
// orthoL2Equidense
arma::mat orthoL2Equidense(arma::mat& X, arma::vec& tGrid);
RcppExport SEXP _DepthInfer_orthoL2Equidense(SEXP XSEXP, SEXP tGridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type tGrid(tGridSEXP);
    rcpp_result_gen = Rcpp::wrap(orthoL2Equidense(X, tGrid));
    return rcpp_result_gen;
END_RCPP
}
// rowMins
List rowMins(const arma::mat& x);
RcppExport SEXP _DepthInfer_rowMins(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rowMins(x));
    return rcpp_result_gen;
END_RCPP
}
// FPCAcov
List FPCAcov(const arma::mat& GaHat, const arma::vec& rho_vec, int h_max);
RcppExport SEXP _DepthInfer_FPCAcov(SEXP GaHatSEXP, SEXP rho_vecSEXP, SEXP h_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type GaHat(GaHatSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type rho_vec(rho_vecSEXP);
    Rcpp::traits::input_parameter< int >::type h_max(h_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(FPCAcov(GaHat, rho_vec, h_max));
    return rcpp_result_gen;
END_RCPP
}
// kFoldCVcpp
arma::vec kFoldCVcpp(const arma::mat& X, const arma::mat& Y, int h_max, int K);
RcppExport SEXP _DepthInfer_kFoldCVcpp(SEXP XSEXP, SEXP YSEXP, SEXP h_maxSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type h_max(h_maxSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(kFoldCVcpp(X, Y, h_max, K));
    return rcpp_result_gen;
END_RCPP
}
// fofrMRtest
List fofrMRtest(const arma::mat& Y, const arma::mat& X, const arma::rowvec& Ybar, const arma::mat& XprojCent, const arma::mat& X0projCent, const arma::vec& gaHat, const arma::mat& phiHat, int h_max);
RcppExport SEXP _DepthInfer_fofrMRtest(SEXP YSEXP, SEXP XSEXP, SEXP YbarSEXP, SEXP XprojCentSEXP, SEXP X0projCentSEXP, SEXP gaHatSEXP, SEXP phiHatSEXP, SEXP h_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type Ybar(YbarSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type XprojCent(XprojCentSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X0projCent(X0projCentSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gaHat(gaHatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type phiHat(phiHatSEXP);
    Rcpp::traits::input_parameter< int >::type h_max(h_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(fofrMRtest(Y, X, Ybar, XprojCent, X0projCent, gaHat, phiHat, h_max));
    return rcpp_result_gen;
END_RCPP
}
// fofrMRtestBTS
Rcpp::List fofrMRtestBTS(const arma::mat& erHat, const arma::mat& Yhat, const arma::mat& X, const arma::mat& phiHat, const arma::vec& gaHat, const arma::mat& X0projCent, const arma::mat& tHatMat, const arma::cube& BhatX0cent_cent, int Mbts);
RcppExport SEXP _DepthInfer_fofrMRtestBTS(SEXP erHatSEXP, SEXP YhatSEXP, SEXP XSEXP, SEXP phiHatSEXP, SEXP gaHatSEXP, SEXP X0projCentSEXP, SEXP tHatMatSEXP, SEXP BhatX0cent_centSEXP, SEXP MbtsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type erHat(erHatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Yhat(YhatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type phiHat(phiHatSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type gaHat(gaHatSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X0projCent(X0projCentSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type tHatMat(tHatMatSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type BhatX0cent_cent(BhatX0cent_centSEXP);
    Rcpp::traits::input_parameter< int >::type Mbts(MbtsSEXP);
    rcpp_result_gen = Rcpp::wrap(fofrMRtestBTS(erHat, Yhat, X, phiHat, gaHat, X0projCent, tHatMat, BhatX0cent_cent, Mbts));
    return rcpp_result_gen;
END_RCPP
}
// AtoB
Rcpp::List AtoB(Rcpp::List A);
RcppExport SEXP _DepthInfer_AtoB(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(AtoB(A));
    return rcpp_result_gen;
END_RCPP
}
