# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FourierBasis <- function(pts, K) {
    .Call(`_DepthInfer_FourierBasis`, pts, K)
}

orthoL2Equidense <- function(X, tGrid) {
    .Call(`_DepthInfer_orthoL2Equidense`, X, tGrid)
}

rowMins <- function(x) {
    .Call(`_DepthInfer_rowMins`, x)
}

FPCAcov <- function(GaHat, rho_vec, h_max) {
    .Call(`_DepthInfer_FPCAcov`, GaHat, rho_vec, h_max)
}

kFoldCVcpp <- function(X, Y, h_max, K) {
    .Call(`_DepthInfer_kFoldCVcpp`, X, Y, h_max, K)
}

fofrMRtest <- function(Y, X, Ybar, XprojCent, X0projCent, gaHat, phiHat, h_max) {
    .Call(`_DepthInfer_fofrMRtest`, Y, X, Ybar, XprojCent, X0projCent, gaHat, phiHat, h_max)
}

fofrMRtestBTS <- function(erHat, Yhat, X, phiHat, gaHat, X0projCent, tHatMat, BhatX0cent_cent, Mbts) {
    .Call(`_DepthInfer_fofrMRtestBTS`, erHat, Yhat, X, phiHat, gaHat, X0projCent, tHatMat, BhatX0cent_cent, Mbts)
}

AtoB <- function(A) {
    .Call(`_DepthInfer_AtoB`, A)
}

